### ISSUE TITLE
wald

### ISSUE THREAD

**Issue by Dura-Europos** [wangh107/lavaan#11]
Validate `wald()` function

Reference

- Source code: https://github.com/yrosseel/lavaan/blob/b46ea82a42ba08a2fa85b9f58c8d9af525cec78c/R/lav_test_Wald.R#L5

**Comment by laywang142** [comment]
notes: 

no error tests: 
- checked example and consistency
- checked instance with one and multiple conditions
- checked verbose option 

error tests: 
- empty constraints
- no equality constraints 
- no convergence
