### ISSUE TITLE
lavTestLRT

### ISSUE THREAD

**Issue by Dura-Europos** [wangh107/lavaan#12]
Validate `LRT()` function

**Comment by laywang142** [comment]
Notes: 

Anova and lavTestLRT should give the same results. 
Return object is a dataframe
Checked various types and methods in order to trigger as many error messages as possible
Checked errors for non-nested models
Non-convergence will trigger two warnings

**Comment by laywang142** [comment]
missing code chunks: 
* Chunks associated to `method = satorra.2000` or `method = satorrabentler2010`
* Trouble triggering `type = cf` properly
* [Df.delta = 0](https://github.com/wangh107/lavaan/blob/master/R/lav_test_LRT.R#L331-L340)
* multiple tests for anova table for single model
