### ISSUE TITLE
upversion to 0.6-18

### ISSUE THREAD

**Issue by Dura-Europos** [wangh107/lavaan#129]

**Comment by laywang142** [comment]
![Image_20240509_143904_243](https://github.com/wangh107/lavaan/assets/122498550/fbd3e508-c60d-4d21-ad6c-474f95bb2255)

expected workflow for now. 

Notes: 

- If there are tests for messages or warnings along the lines of "I'll add this later", just delete those tests and make note of them. 
- Rule of thumb: if it fixes the tests, then it's fine.

**Comment by Dura-Europos** [comment]
Individual runs; files without problem:
- [ x] test-anova.R
- [ x] test-fitMeasures.R
- [ ] test-efa.R
- [ x] test-lav_object_inspect_se.R
-
