### ISSUE TITLE
sem

### ISSUE THREAD

**Issue by Dura-Europos** [wangh107/lavaan#4]
Validate `sem()` function

Reference:
- Tutorial: https://lavaan.ugent.be/tutorial/sem.html
- Source code: https://github.com/yrosseel/lavaan/blob/5835901b9e2f07248e443a6a1b905721ea4c06ad/R/xxx_lavaan.R#L2176

**Comment by laywang142** [comment]
notes: 

- sem() doesn't really have a lot of explicitly written errors or warnings so most of the tests are just checking for consistency. 
- sem is a wrapper for lavaan() so check equivalence there
- checked summary outputs when checking equivalence for simplicity
- sem() itself should return object of s4 class "lavaan"

**Comment by Dura-Europos** [comment]
`sem` and `cfa` are defined using the same function.

Merge sem to cfa and close this issue. Please go to #15
