### ISSUE TITLE
lavTest

### ISSUE THREAD

**Issue by laywang142** [wangh107/lavaan#56]
called by #12 #24 

source code [here](https://github.com/wangh107/lavaan/blob/48886be1248c9b0ec9b85551c2e440e04df611b5/R/lav_test.R#L4)

**Comment by Dura-Europos** [comment]
# Problem

1. This code extracts tests even though it may not make sense
```
lavTest(fit, scaled.test = 456)
```
2. test and scaled.test input: non-character in a vector that contains string is not caught in this function
```
lavTest(fit, test = c("standard", 123))

lavTest(fit, test = "standard", scaled.test = c("standard", 456))
```

**Comment by Dura-Europos** [comment]
# Principles

- Input validation: providing invalid output, test, and scaled.test arguments and checking if the function raises the expected errors.
   - handling of special cases: "none" or "bootstrap" tests.
- Test selection: providing different combinations of test and scaled.test arguments and verifying that the correct tests are selected and ordered correctly.
- Output formatting: setting output to "list" and "text" and verifying that the returned object or printed output is in the expected format.
