### ISSUE TITLE
fitMeasures

### ISSUE THREAD

**Issue by Dura-Europos** [wangh107/lavaan#6]
Validate `fitMeasures()` function

Example run from Ying-Fang:
```
library(lavaan)
data = HolzingerSwineford1939
model_1<- 'f  =~ x1 + x2 + x3 + x4 + x5 + x6+  x7 + x8 + x9 '
fit_1 <- cfa(model_1, data = data)
fit.subset<-c("chisq.scaled","df","pvalue.scaled",
              "rmsea.scaled","rmsea.pvalue.scale",
              "rmsea.ci.lower.scaled","rmsea.ci.upper.scaled",
              "cfi","tli","srmr","rmsea","aic","bic")
fit.summary <- round(fitmeasures(fit_1, fit.subset),3)
```

Source code: https://github.com/wangh107/lavaan/blob/e9ec24447ce05a91ce1239d47444a474fdbf90e9/R/lav_fit_measures.R#L17

**Comment by laywang142** [comment]
notes: 

No errors: 
- check if can reproduce example output (consistency and stuff)
- fitMeasures has a few aliases so checked to see if those worked too
- check if default arguments work or not
- checked different combinations of estimators and measures
- checked efaList options and cfa options
- tried output options

errors:
- checked explicitly written error messages
- note: for the case of non-convergence, there can sometimes be both a warning message from something like cfa() and an additional error message from fitmeasures(). Need to account for both in the test.

**Comment by laywang142** [comment]
<img width="647" alt="Screenshot 2024-03-07 at 11 41 40 AM" src="https://github.com/wangh107/lavaan/assets/122498550/e149950f-f718-4881-b91c-091c9948a273">

fitMeasures (the exported function) calls lav_fit_measures (which isn't exported). Adjusted tests to be specific for fitMeasures (?)
